### ISSUE TITLE
Toggle Line Comment command does not function

### ISSUE THREAD

**Issue by KazNX** [kriegalex/vscode-cuda#3]
Using the "Toggle Line Comment" command (hot key: "Ctrl+/" or "Command+/") does nothing. It should comment the current line or selected lines using line comments "//".

**Comment by kriegalex** [comment]
Will look at it during the holidays, thanks for the report

**Comment by KazNX** [comment]
Sorry, I think I reported this against the wrong plugin. Should have been against OpenCL.
