### ISSUE TITLE
debug disabled for cuda code in vscode

### ISSUE THREAD

**Issue by WZRPW** [kriegalex/vscode-cuda#4]
hi there, I installed the vscode-cuda. I cannot add breakpoint in .cu file of my project in Ubuntu OS. For the windows version of the same project, I have no problem in adding breakpoint in .cu files. I wonder if this is a problem associated with vscode-cuda or VSCODE itself. Thanks,

**Comment by kriegalex** [comment]
I think that debugging support is in the same basket as Intellisense. If you don't explicitly implement the feature, it won't work like in the C++ plugin. 

This plugin is aimed at giving you code coloring and snippets, not full debugging environment.

I had this [repo](https://github.com/kriegalex/vscode-cudatools) started to do that, but it is actually a lot of work. If someone wants to do it, ok for me 👍
