### ISSUE TITLE
support for cpp files

### ISSUE THREAD

**Issue by nhrnhr0** [kriegalex/vscode-cuda#5]
when compile like this: "nvcc -x cu main.cpp" a cpp file the contain cuda code like kernals and everything else but the extension dose not recognizes the symbols like __global__ ext....
jest add cpp to the "File Extensions"

https://i.ibb.co/Ryf1tHv/Screenshot-from-2019-05-15-14-04-12.png

**Comment by kriegalex** [comment]
Hi,
By standards, if your file contains CUDA code, kernels, etc..., your file extension should be .cu, not cpp. If I add the cpp file extension, this plugin will conflict with the official C++ plugin that a lot of people are probably using next to CUDA.
Please consider the two following options:

- Use .cu as file extension and then compile without the -x option
- If your project is big with too many CUDA cpp files to rename, please tell VSCode to use the CUDA extension manually by editing the settings
![image](https://user-images.githubusercontent.com/2486182/57784384-1bcbfe00-7730-11e9-95ec-6b397cf8dd0f.png)
