### ISSUE TITLE
How about making it suggest based on intelliSense?

### ISSUE THREAD

**Issue by wow056** [kriegalex/vscode-cuda#6]
This plugin is so good because it does not show red-line under <<< and >>> because Visual Studio show annoying red-line under these expressions.
However, I think it helps coding with C++ suggestion and auto completion of IntelliSense.
Do you mind of adopting it?

**Comment by hedi-sel** [comment]
I completely agree. 
I think it is an absolute priority that all the features of the C++ extension should be kept for the CUDA C++ extension.
For now, as it is, writing a .cu file with this extension is almost like using a text editor.

**Comment by kriegalex** [comment]
> For now, as it is, writing a .cu file with this extension is almost like using a text editor.

That is exactly the description of my plugin in the README: syntax + snippets.
> I think it helps coding with C++ suggestion and auto completion of IntelliSense

In the README, this is mentioned in the known issues section. I created another project for this feature, but I have no time these days to implement it, as I use CLion now. I tried to do it after I finished this plugin 2 years ago, but you could not simply "include" Intellisense for C++ and tweak it for CUDA (like I did for this plugin). Maybe now it is possible. 

I encourage anyone to send PRs to the other project. If both projects become stable and maintained, I could merge them in this one and add more admin roles from the contributors of the other project. I separated the projects to keep things clean, when I saw that Intellisense was no easy thing.
