### ISSUE TITLE
nvcc : The term 'nvcc' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by soosan94** [kriegalex/vscode-cuda#9]
I want to execute file 'test_nvcc.cu' by command 'nvcc test_nvcc.cu -o test_nvcc -run',
but I got error message: "nvcc : The term 'nvcc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Do you have any idea about this?

**Comment by naveensaigit** [comment]
You have to add `nvcc` to PATH

**Comment by kriegalex** [comment]
> You have to add `nvcc` to PATH

This is true. Please consider taking 10 minutes to read the CUDA installation doc. [Here you go](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html)

**Comment by kriegalex** [comment]
There is a big issue with this project. People keep thinking it is an all-in-one package that adds full cuda coding capabilities, where the readme clearly says it is just for snippets and code coloring.

I may need to change the title or republish it with another name.

**Comment by soosan94** [comment]
Thank you.
